### PR TITLE
drivers/ovsdbDriver.go: fix govet UUID

### PR DESCRIPTION
**Pull request by unclejack**

### CODE REVIEW

**Comment by unclejack** [comment]
This is green now. 

ping @jojimt @abhinandanpb @erikh @gaurav-dalvi

**Comment by abhinandanpb** [comment]
LGTM. Any reason why this was not hit when the PR that changed this went thru the sanity run ?

**Comment by unclejack** [comment]
@abhinandanpb I don't know right now. I've hit it on my host during the checks.

**Comment by dseevr** [comment]
@unclejack  Weird, I just tested the `[]Foo{{"bar"}}` declaration style with `go vet` on 1.7.3 and 1.5.0 and neither of them complained about it.  I'm curious what the exact error output you got was.

**Comment by erikh** [comment]
Yeah I'm seeing it too, I think it's a golint/go vet version issue

**Comment by unclejack** [comment]
@erikh is probably right. I've seen this happen after switching to Go 1.7.3.

**Comment by erikh** [comment]
Let's merge this if we can today, #610 depends on this which I hope to have ready by EOW.

**Pull request merged**
