### PR TITLE
return error while deleting network with active EPs. fixes#270

### PR DESCRIPTION
**Pull request by vvb**
The error returned by DeleteDockNet needs to be passed back to make sure the overall operation fail.

### CODE REVIEW

**Comment by shaleman** [comment]
@vvb changes look good.
But, this will work only in docker plugin mode. It'll not work in Kubernetes and mesos which will not have a network concept. Best might be to rely on 'EpCount' field in network state and reject the deletion till all endpoints are removed.. Something to think about if you are adding unit tests for these..

**Comment by vvb** [comment]
@shaleman Added a check for EpCount a level higher so as to abstract it from underlying container runtime. Also added a unit-test that tests for this case. I have refactored DeleteNetworks a little bit, to use the existing DeleteNetworkID method. 

```
vagrant@netplugin-node1:~$ netctl tenant create pepsi
INFO[0000] Creating tenant: pepsi
vagrant@netplugin-node1:~$ netctl net create net1 --subnet=20.1.1.0/24 --gateway=20.1.1.254 --pkt-tag=1002 --tenant pepsi
vagrant@netplugin-node1:~$ netctl net delete --tenant pepsi net1
INFO[0000] Deleting network pepsi:net1
vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ netctl net create net1 --subnet=20.1.1.0/24 --gateway=20.1.1.254 --pkt-tag=1002 --tenant pepsi
vagrant@netplugin-node1:~$ docker run -itd --name=web --net=net1/pepsi ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
92ec6d044cb3: Pull complete
2ef91804894a: Pull complete
f80999a1f330: Pull complete
6cc0fc2a5ee3: Pull complete
Digest: sha256:457b05828bdb5dcc044d93d042863fba3f2158ae249a6db5ae3934307c757c54
Status: Downloaded newer image for ubuntu:latest
28090b634864e97433d1bfb03076be68a0b4535a9b21a3667d3fc3b03d1f7e28
vagrant@netplugin-node1:~$
vagrant@netplugin-node1:~$
vagrant@netplugin-node1:~$ netctl net delete --tenant pepsi net1
INFO[0000] Deleting network pepsi:net1
ERRO[0000] 500 Internal Server Error: network net1/pepsi has active endpoints
vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ docker run -itd --name=web1 --net=net1/pepsi ubuntu /bin/bash
58d233fc9c88d3126fb80490e78ce440b73bcd8cafb72104533b8bb3c8bb253b
vagrant@netplugin-node1:~$
```

**Comment by jainvipin** [comment]
:+1:  @vvb

**Comment by shaleman** [comment]
Awesome! thanks @vvb 
minor: You might want to check for EpCount after detaching skydns container.. Else it might always be one.

**Comment by shaleman** [comment]
LGTM

**Pull request merged**
