### PR TITLE
implement changes to be able to make releases

### PR DESCRIPTION
**Pull request by unclejack**
This PR implements the changes needed to release netplugin.

Fixes #699

### CODE REVIEW

**Comment by unclejack** [comment]
@rhim: Sure, I'll make those changes as well.

**Comment by dseevr** [comment]
@unclejack can you retrigger CI on this if you've made all the changes @rhim requested?

**Comment by unclejack** [comment]
I haven't made those changes yet. Please allow me to update this PR tomorrow. I'll ping you to review again.

**Comment by unclejack** [comment]
@dseevr @rhim PTAL

**Comment by dseevr** [comment]
LGTM, thanks for doing this

**Comment by jojimt** [comment]
@unclejack Can you please trigger sanity?

**Comment by unclejack** [comment]
@jojimt: This is green now. PTAL

**Pull request merged**
