### PR TITLE
Makefile: build tarballs on CI

### PR DESCRIPTION
**Pull request by unclejack**
This PR adds the tar target to the list of targets which are called on the CI. This should make this less likely to break when changes are made.

### CODE REVIEW

**Comment by unclejack** [comment]
build PR

**Comment by unclejack** [comment]
This is WIP. I'm looking into adding some other targets to this list.

**Comment by chrisplo** [comment]
build PR

**Comment by unclejack** [comment]
This is green. @dseevr: PTAL

**Pull request merged**
