### PR TITLE
Changing default mode to vrouter

### PR DESCRIPTION
**Pull request by abhinandanpb**

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM, just curious we are setting `vrouter` mode just for vxlan network type, do we need to do it for vlan networks as well?

**Comment by abhinandanpb** [comment]
@mapuri for vlan networks i am trying to add a new mode called vlrouter mode. vrouter mode primarily is for vxlan networks only.

**Comment by mapuri** [comment]
ok, sounds good.

**Comment by shaleman** [comment]
@abhinandanpb can you godep import latest ofnet, run sanities and resubmit this PR?

**Pull request closed without merging**
