### PR TITLE
Fixing vagrant1.8.5 issue

### PR DESCRIPTION
**Pull request by gaurav-dalvi**
This is to take care of the issue : https://github.com/contiv/netplugin/issues/495

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
Tested this for following scenarios.

Running `make system-test` on Centos 7 as host OS
1: Vagrant 1.8.4 with VirtualBox 5.1
2: Vagrant 1.8.5 with VirtualBox 5.1
3: Vagrant 1.8.4 with VirtualBox 5.0
4: Vagrant 1.8.5 with VirtualBox 5.0

**Comment by gaurav-dalvi** [comment]
Tested this for following scenarios as well.

Running make system-test , make demo ,make ssh-build on Centos 7 as host OS
1: Vagrant 1.8.4 with VirtualBox 5.1 -- ubuntu1604 -- not working
```
CONTIV_NODE_OS=ubuntu make demo
make ssh-build
make[1]: Entering directory `/home/admin/GAURAV/src/github.com/contiv/netplugin'
vagrant box update
The provider 'virtualbox' that was requested to back the machine
'netplugin-node1' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
make[1]: *** [update] Error 1

```

2: Vagrant 1.8.5 with VirtualBox 5.1 -- ubuntu1604 -- working !

**Comment by shaleman** [comment]
LGTM

**Comment by gaurav-dalvi** [comment]
Closing. Will raise new PR as master branch is way ahead ! and Its just one line change.

**Pull request closed without merging**
