### PR TITLE
Wait for OVS switch connect - fix netplugin restart crash

### PR DESCRIPTION
**Pull request by DivyaVavili**

### CODE REVIEW

**Comment by shaleman** [comment]
LGTM

**Comment by shaleman** [comment]
LGTM
We can merge this once sanity passes

**Comment by vvb** [comment]
@DivyaVavili LGTM

we might require another change in the same function.. at 
```
    // Create OVS db driver
    sw.ovsdbDriver, err = NewOvsdbDriver(bridgeName, "secure")
    if err != nil {
        log.Fatalf("Error creating ovsdb driver. Err: %v", err)
    }
```
we seem to be using it even if the above failed,
```
if !sw.ovsdbDriver.IsControllerPresent(target) {
```

**Comment by vvb** [comment]
ah! my bad! missed the Fatalf

**Comment by shaleman** [comment]
This was merged as part of #325

**Comment by shaleman** [comment]
This was merged as part of #325

**Pull request closed without merging**
