### PR TITLE
Deleted flow cache in vlrouter when removing local endpoint

### PR DESCRIPTION
**Pull request by zhouzijiang**
#### Type of fix: Bug Fix
Please describe:
- changes made in the Pull request
    deleted flow cache in vlrouter when removing local endpoint, or the flow cache in vlrouter will never be deleted.
- type of testing done (both manual and automated)
    manual test have been done.
## TODO
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by zhouzijiang** [comment]
@tiewei  please review it, thanks!

**Comment by tiewei** [comment]
usually updating vendor codes are not allowed in golang project

**Comment by vhosakot** [comment]
> usually updating vendor codes are not allowed in golang project

I agree, I'd update the ofnet in godep (https://github.com/contiv/netplugin/blob/master/Godeps/Godeps.json) to the right git sha.

**Comment by zhouzijiang** [comment]
@tiewei @vhosakot  ok, I wil create a pull request in ofnet repository

**Pull request closed without merging**
