### PR TITLE
Netmaster changes

### PR DESCRIPTION
**Pull request by shaleman**
Various net master changes:

 - Separate out docker network code into separate package
    - Store docker network to UUID mapping as docknet state and use that to derive network/service names during lib network API calls(So that we don't need to query docker for this info). 
    - Add unit test for docker network APIs
 - Change rules to take from/to endpoint-groups instead of just end-point-group for clarity.
    - Make corresponding contiv model and netctl CLI changes
    - Change 'accept' action to 'allow' action
 - Change netctl to use auto-generated contiv-model go-client
 - Add unit test for net master REST apis.
 - Fix minor bugs found while adding unit test for netmaster REST apis

### CODE REVIEW

**Comment by shaleman** [comment]
Folks, can someone review this change?

**Comment by shaleman** [comment]
I'm going to rebase and merge this PR if there are no further comments

**Comment by jojimt** [comment]
LGTM

**Comment by jainvipin** [comment]
LGTM

**Pull request merged**
