### PR TITLE
access k8s services using cluster-ip

### PR DESCRIPTION
**Pull request by rchirakk**
fixes kube-dns failures.
fixes https://github.com/contiv/netplugin/issues/878,
https://github.com/contiv/netplugin/issues/864

Signed-off-by: Ranjith <rchirakk@users.noreply.github.com>

### CODE REVIEW

**Comment by DivyaVavili** [comment]
@rchirakk: The fix LGTM for vxlan networks. How would we handle reachability of cluster IP in vlan network?

**Comment by srampal** [comment]
@DivyaVavili I discussed this topic with Joji before he left. He indicated this host access should be only for the vxlan case and for the vlan case we should do it via external path. I am not sure about that and would like to revisit this with you.  Meanwhile I think we should let this fix go in for the vxlan case and come back to the vlan case in a followup issue if we all agree it needs to address that as well.Currently the contivh1 path is anyway not used for the vlan case and we can revisit that. Meanwhile, this fix can go ahead and get merged for the vxlan case.

**Comment by DivyaVavili** [comment]
Let's not merge this yet. This fix is not required for pod-to-pod communication over cluster-IP. The changes here allow the host to access the services via cluster IP from the cluster nodes. Is there a use-case which requires this?

**Comment by srampal** [comment]
@DivyaVavili This is definitely needed asap.   The use case is for Openshift (for example when using the Openshift Docker registry)

**Comment by DivyaVavili** [comment]
@srampal: Currently we don't see any use-case for this. We need to have a discussion to understand the use-case for Openshift. Let's follow it up on a separate channel.

**Comment by srampal** [comment]
I think the confusion has been on how we define the meaning of "use case". There is a valid use case for the original issue (being able to access k8s services from the host). However the term "use case" in your comment referred to the *currently proposed fix* which is simply adding a static route towards cluster IPs and may not be the right fix. So the *use case* is certainly valid but the *current fix* may not be the right one.

**Comment by rchirakk** [comment]
reopening the PR

**Comment by srampal** [comment]
Double checking the static route solution proposed earlier. Looks like it is the right fix for this case because Linux source IP selection is based on which outgoing interface to use for the best next hop towards the destination and then use the primary IP address from that outgoing interface.  Will double check this with some folks in case yet another solution option is possible else we should merge the static route

**Comment by srampal** [comment]
Didnt mean to close the PR ...

**Pull request merged**
