### PR TITLE
Support secure etcd connection with tls cert

### LINKED ISSUE #777: Proposal: support to run against secured etcd
In production, ETCD should be secured with TLS to ensure the security and stability, but Contiv currently does not support secured etcd. This is an essential feature when use Contiv in produtin, any plan to support this?

### PR DESCRIPTION
**Pull request by BSWANG**
#### Fixes #777 
Please describe:
- support secure etcd connection with tls cert
- manual tested on secure etcd server

## TODO
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by tiewei** [comment]
build PR

**Comment by dseevr** [comment]
Failing here:

```
# github.com/contiv/netplugin/netmaster/objApi
netmaster/objApi/apiController.go:70: undefined: modeldb.InitWithConfig
```

(sorry, we currently don't have public CI runs)

**Comment by BSWANG** [comment]
@dseevr @tiewei 
Sorry, I will fix it then reopen this pr.

**Comment by dseevr** [comment]
@BSWANG I noticed you have forked the `objdb` repo... that repo was moved to "contiv-experimental" because we `git subtree`'d it into the netplugin repo (see the "objdb" directory there).  You don't need to have a fork of that repo.  I'll add a note on the repo that it's not used anymore.

**Comment by BSWANG** [comment]
@dseevr Thanks for your advise. Due my force pushed to my branch, can not reopen it. I will open another PR.

**Pull request closed without merging**
