### PR TITLE
Godeps,vendor: update contivmodel to the latest version + use new objdb import paths

### PR DESCRIPTION
**Pull request by dseevr**
Signed-off-by: Bill Robinson dseevr@users.noreply.github.com

### CODE REVIEW

**Comment by dseevr** [comment]
build pr

**Comment by unclejack** [comment]
build PR

**Comment by dseevr** [comment]
build pr

**Comment by dseevr** [comment]
build pr

**Comment by unclejack** [comment]
build PR

**Comment by unclejack** [comment]
build PR

**Pull request merged**
