### PR TITLE
add short sanity make target

### PR DESCRIPTION
**Pull request by unclejack**

### CODE REVIEW

**Comment by jainvipin** [comment]
+1for shorter tests; however shorter tests shouldn't become substitute for full sanity pass needed for upstreaming it.

**Comment by unclejack** [comment]
@jainvipin This isn't hooked into any other suites and it's not meant for CI. This is only to be used during the development cycle (make changes, test, make more changes, test and so on).

**Comment by shaleman** [comment]
LGTM

**Comment by shaleman** [comment]
@unclejack can you retrigger sanity run for this PR? Jenkins had some problem last week and sanity failed for this PR.

**Comment by unclejack** [comment]
@shaleman PTAL, it should be fine now.

**Comment by shaleman** [comment]
LGTM

**Pull request merged**
