### PR TITLE
Vagrantfile: added ability to install Docker EE (specified version) on centos

### PR DESCRIPTION
**Pull request by dseevr**
envvar name is copied from https://docs.docker.com/engine/installation/linux/docker-ee/centos/

driveby: fixed a bug where `node_os` was an empty string instead of the default value because `ENV["CONTIV_NODE_OS"]` was being set to an empty string in the `make` target

Signed-off-by: Bill Robinson <dseevr@users.noreply.github.com>

### CODE REVIEW

**Comment by unclejack** [comment]
@dseevr: Can you provide some steps to know how to test this, please?

**Comment by dseevr** [comment]
```sh

**Comment by dseevr** [comment]
build pr

**Comment by unclejack** [comment]
build PR

**Comment by dseevr** [comment]
build pr

**Pull request merged**
