### PR TITLE
Vagrant and Docker script changes for consul cluster integration

### PR DESCRIPTION
**Pull request by mapuri**
This set of changes brings in necessary scripting and configuration to bring up a consul cluster in our test/demo environments.

In subsequent PRs I shall bring in consul integration with the netplugin.

**Note:** As part of docker-in-docker script changes, I have moved to using the customized ubuntu image (viz. contiv/ubuntu) that is published and pulled from docker-hub. That image get's updated everytime a change is pushed to our Dockerfile in the repo (by using the automated-build feature of docker hub). This relieves us of managing the image every time Dockerfile changes. But this requires us to push Dockerfile to github first, which implies it requires some manual testing of image on Dockerfile editor's end. I need to see if I can eliminate this requirement while keeping goodness of automated-build.

### CODE REVIEW

**Comment by jainvipin** [comment]
@mapuri - I understand you already merged the changes; one small question - do we bring up both clusters (etcd and consul) with these changes and per the choice of runtime use one or the other?

**Comment by mapuri** [comment]
> do we bring up both clusters (etcd and consul) with these changes and per the choice of runtime use one or the other?

Yes, that is correct. For the test/demo environment I bring-up both the data stores. The idea is to be able to run systemtests for both the data-stores in one spin-up of the test environment. The data store will be chosen based on the configuration settings (for netplugin, netdcli etc). A little bit refactoring of code is needed there, which I am planning to push in my next PR.

**Comment by erikh** [comment]
I’m seeing some heisenbugs in the unit tests surrounding consul testing. Is it related to this patch?

**Comment by mapuri** [comment]
@erikh do you have failed test logs? I can check. There were some timing related conditions around updating state and starting watch back to back in the tests for which I had added a workaround by adding a sleep. Are you seeing failures in Watch related tests?

**Pull request merged**
