### PR TITLE
scripts/unittests: add per test timeouts

### PR DESCRIPTION
**Pull request by unclejack**
This PR adds timeouts to the unit tests.

### CODE REVIEW

**Comment by dseevr** [comment]
Thanks for doing this 👍

**Comment by gaurav-dalvi** [comment]
LGTM.

**Comment by erikh** [comment]
10m is the default go test timeout. This doesn't really solve much unless I'm missing something?

**Comment by unclejack** [comment]
@erikh This is what I've found in the source code:
```
timeout          = flag.Duration("test.timeout", 0, "if positive, sets an aggregate time limit for all tests")
```

**Comment by erikh** [comment]
```
        -timeout t
            If a test runs longer than t, panic.
            The default is 10 minutes (10m).
```

**Comment by erikh** [comment]
I strong suggest making it variable so we can drive it through the environment (and adjust it at the CI level).

**Comment by unclejack** [comment]
@erikh I've updated it to make it specify 10m by default and override it when the env var is set. A default of ten minutes makes sense now. We don't need special cases to not specify the timeout and it just falls back to the default. PTAL

**Pull request merged**
