### PR TITLE
Godeps,vendor: Cleanup godeps + update contivmodel to be threadsafe

### PR DESCRIPTION
**Pull request by erikh**
* _workspace is no longer used
* godeps was still hooked on 1.6 semantics, moved to 1.7
* latest version of github.com/tools/godep (aka, update your copy)
* removes many orphaned files

Signed-off-by: Erik Hollensbe <github@hollensbe.org>

### CODE REVIEW

**Comment by DivyaVavili** [comment]
@erikh: Does this also cover the changes made in PR #580? The PR was not merged coz of intermittent sanity failures. If it's overlapping, I can close the other PR.

**Comment by erikh** [comment]
@DivyaVavili not exactly. this is removal of those files not directly. we're clearing the whole vendor and removing any unnecessary files, and running godep to replace hte ones that existed before.

**Comment by erikh** [comment]
@jojimt @DivyaVavili I'm also adding the contivmodel changes so I can test them here. see contiv/modelgen#16 for more information.

**Comment by erikh** [comment]
don't merge this yet, it's missing a modelgen update.

**Comment by erikh** [comment]
As the topic change indicates, this also incorporates changes from contiv/contivmodel#45 to enable locking across the platform.

**Comment by erikh** [comment]
@gaurav-dalvi @dojacobs this now has a doc rewrite for godep + make tasks to update godep, can you review?

**Comment by gaurav-dalvi** [comment]
@erikh : Thanks for the docs. It looks good. So If I make change in contiv/modelgen repo , and If i need to vendor that in contiv/netplugin, I just need to follow the workflow you mentioned ?

**Comment by erikh** [comment]
modelgen is different, I'll send a PR there with workflow info.

**Comment by erikh** [comment]
@jojimt ready for review/merge. This should improve test stability.

**Pull request merged**
