### PR TITLE
making the cli consistent with docker. resolves #239

### LINKED ISSUE #239: make netctl cli consistent with `docker network`
It is often difficult to remember and use various options in `netctl net` command options. Would it make sense to keep ti consistent to `docker network` cli? I am opening the thread to discuss this:

Consider the two:

######  Docker Network Options
```
Usage:	docker network [OPTIONS] COMMAND [OPTIONS]

Commands:
  create                   Create a network
  connect                  Connect container to a network
  disconnect               Disconnect container from a network
  inspect                  Display detailed network information
  ls                       List all networks
  rm                       Remove a network
```

###### Whereas `netctl net` output is:

```
NAME:
   netctl net - Network manipulation tools

USAGE:
   netctl net command [command options] [arguments...]

COMMANDS:
   list		List networks
   delete	Delete a network
   create	Create a network
   help, h	Shows a list of commands or help for one command
   
OPTIONS:
   --help, -h	show help
```

It seems it would be good to change netctl commands to map
- list --> ls
- delete --> rm
- create --> create (same)
- inspect --> should we implement (along the lines of `docker network inspect`

Of course, this means we change the verbs for all commands, then - like `policy`, `tenant`, etc.

@unclejack, @erikh, @mapuri, @shaleman, @jojimt - WDYT?

### PR DESCRIPTION
**Pull request by vijayvikrant**
(1) Making the netctl cli commands consistent with docker
(2) while still retaining the existing commands as aliases for allowing users the freedom to choose.
This will also make sure that all documentation would still be valid post this change.

```
vagrant@netplugin-node1:~$ netctl tenant create -p 10.1.1.1/16 -v 100-101 -x 200-300 pepsi
INFO[0000] Creating tenant: pepsi
vagrant@netplugin-node1:~$ netctl tenant ls
Name     Subnet Pool    Subnet Len  vlans       vxlans
------   -----------    ----------  -----       ------
default  10.1.1.1/16    24          100-1100    1001-1100
pepsi    10.1.1.1/16    24          100-101     200-300

vagrant@netplugin-node1:~$ netctl network ls
Tenant  Network  Encap type  Packet tag  Subnet   Gateway
------  -------  ----------  ----------  -------  ------
vagrant@netplugin-node1:~$
vagrant@netplugin-node1:~$ netctl network create -p 200 -s 10.1.1.1/16 -g 10.1.1.1 -t pepsi pepsi-net
vagrant@netplugin-node1:~$
vagrant@netplugin-node1:~$ netctl network ls --tenant pepsi
Tenant  Network    Encap type  Packet tag  Subnet       Gateway
------  -------    ----------  ----------  -------      ------
pepsi   pepsi-net  vxlan       200         10.1.1.1/16  10.1.1.1
vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ netctl network rm pepsi-net --tenant pepsi
INFO[0000] Deleting network pepsi:pepsi-net
vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ netctl group ls
Tenant  Group  Network  Policies
------  -----  -------  --------
vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ netctl  policy
NAME:
   netctl policy - Policy manipulation tools

USAGE:
   netctl policy command [command options] [arguments...]

COMMANDS:
   create       Create a new policy
   rm, delete   Delete a policy
   ls, list     List policies
   help, h      Shows a list of commands or help for one command

OPTIONS:
   --help, -h   show help

vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ netctl network
NAME:
   netctl network - Network manipulation tools

USAGE:
   netctl network command [command options] [arguments...]

COMMANDS:
   ls, list     List networks
   rm, delete   Delete a network
   create       Create a network
   help, h      Shows a list of commands or help for one command

OPTIONS:
   --help, -h   show help
vagrant@netplugin-node1:~$

vagrant@netplugin-node1:~$ netctl group
NAME:
   netctl group - Endpoint Group manipulation tools

USAGE:
   netctl group command [command options] [arguments...]

COMMANDS:
   create       Create an endpoint group
   rm, delete   Delete an endpoint group
   ls, list     List endpoint groups
   help, h      Shows a list of commands or help for one command

OPTIONS:
   --help, -h   show help

vagrant@netplugin-node1:~$
```

### CODE REVIEW

**Comment by vijayvikrant** [comment]
should `netctl rule add` also be changed to `netctl rule create` ??

**Comment by shaleman** [comment]
LGTM.
@vijayvikrant IMHO "rule add" is more natural than "rule create". idea being rule is being added to an existing policy. Basically, you are 'creating' a policy and 'adding' rule to a policy.

**Comment by jainvipin** [comment]
@shaleman - I understand, however consistency will prevail and so keeping it to `rule create`

**Comment by vijayvikrant** [comment]
@jainvipin @shaleman In that case, I will change it to `rule create` and have `rule add` as an alias.

**Comment by jainvipin** [comment]
SGTM @vijayvikrant

**Comment by vijayvikrant** [comment]
@jainvipin @shaleman I have made this change for `rule create`. PTAL

**Comment by jainvipin** [comment]
LGTM

**Pull request merged**
