### PR TITLE
testing: migrate from gopkg.in/check.v1 to fork

### PR DESCRIPTION
**Pull request by unclejack**
This PR makes the required changes to migrate away from gopkg.in/check.v1. The fork includes useful features and fixes already:
- timeouts for each test which stop the whole suite
- flag to stop running the tests when a test fails
- a fix to avoid creating predictable temporary directories for testing

The first commit is already good to go. More commits will be added to start making use of the new features.

### CODE REVIEW

**Comment by jojimt** [comment]
Can we avoid forks? What exactly is it buying us? If we don't have choice other than fork, can we fork it under contiv?

**Comment by unclejack** [comment]
@jojimt: The main repository has many unmerged PRs. There's no way to avoid a fork. I've had this under my handle so I could work on it and be responsible for the improvements made to it.

**Comment by unclejack** [comment]
ping @dseevr @jojimt @rhim

This PR is green now. This PR will help us with the CI. Once a test fails in the system tests, the tests won't continue. The requested changes have been made. PTAL

**Comment by jojimt** [comment]
I am still not sure this is the right thing to do. We are essentially moving away from the standard go package here. Let's have some discussions before we do this.

**Comment by unclejack** [comment]
@jojimt: That's not a standard package. It's gopkg.in/check.v1.

**Comment by jojimt** [comment]
Let's talk about this in the team and reach a conclusion.

**Comment by unclejack** [comment]
@jojimt: This PR is green. `contiv/check` is used now. PTAL

**Comment by dseevr** [comment]
@unclejack could you address the `test/systemtests/hostaccess_test.go:6:2: cannot find package "gopkg.in/check.v1" in any of:` error and repush this?

We agreed to switch to this fork two months ago, so let's push to get it done now 😄

**Comment by dseevr** [comment]
@unclejack could you rebase this?

**Comment by unclejack** [comment]
@dseevr: It's done. PTAL

**Comment by dseevr** [comment]
@unclejack LGTM

@gkvijay this is ready for your review + merge

**Pull request merged**
