### PR TITLE
delete unused BGP field.

### PR DESCRIPTION
**Pull request by rchirakk**
Signed-off-by: Ranjith <rchirakk@users.noreply.github.com>

### CODE REVIEW

**Comment by gkvijay** [comment]
Hostname is a required field for BGP commands. It identifies the netplugin instance on which BGP is being created/deleted.

**Comment by rchirakk** [comment]
hostname is mandatory argument.
It had another option --hostname, which is removed here.

**Comment by g1rana** [comment]
LTM

**Comment by g1rana** [comment]
LGTM

**Comment by abhinandanpb** [comment]
LGTM

**Pull request merged**
