### PR TITLE
Makefile,Vagrantfile: Build on 1.7.3

### LINKED ISSUE #588: update to the latest Go version
Netplugin is currently using Go 1.5. Go 1.7.3 is the latest.

We need to update to the latest version. This issue will track the tasks required to get this done.

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe github@hollensbe.org

Fixes #588

### CODE REVIEW

**Comment by dseevr** [comment]
@erikh I can't edit the description here, but you could add `Fixes #588` to this one

**Comment by erikh** [comment]
@abhinandanpb same issue with the CI? should I retrigger?

**Comment by abhinandanpb** [comment]
@erikh  did u rebase ?

**Comment by erikh** [comment]
oh ok, didn't realize I had to. done on all my PRs.

**Comment by abhinandanpb** [comment]
LGTM

**Comment by unclejack** [comment]
LGTM

**Pull request merged**
