### PR TITLE
test/systemtests: fix errors to pass golint

### PR DESCRIPTION
**Pull request by unclejack**
This PR fixes some issues encountered when setting up a new build environment. A new version of golint discovered these issues. This was breaking the build.

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
LGTM.

` Change is having first alphabet in log message as small case `.  I am surprised why golang has such a strict coding guidelines. (Declaration of variable, structure of for loop is ok but why first alphabet as small case.  )

**Comment by unclejack** [comment]
@gaurav-dalvi There are other issues. These ones were the ones which were stopping me from building the binaries.

**Comment by erikh** [comment]
I already fixed all of this I'm pretty sure?

**Comment by erikh** [comment]
golint vs. the tests? I hope we're not sincerely considering doing this long-term. it's going to be a significant time drain.

**Comment by unclejack** [comment]
@erikh: This was picked up by golint during `make run-build` for some reason.

**Comment by erikh** [comment]
Hmm. Maybe it’s time to fork golint so we don’t have to constantly chase this crap.

@jojimt?

**Comment by unclejack** [comment]
Maybe we only need to exclude the tests folder from golint for now.

**Comment by erikh** [comment]
I know what the problem is here now.

`aci_util.go` is not treated as a test file. I fixed this in the test improvements branch.

**Comment by erikh** [comment]
https://github.com/erikh/netplugin/commit/e92c195e235eb5e726427403d7963f7a0fe6ba40 fwiw. I can rebase over your changes if they're breaking things currently, but I don't see how they are considering master built last night.

**Comment by unclejack** [comment]
I'll double check with master again and comment on this PR again.

**Comment by unclejack** [comment]
I'm closing this for now.

**Pull request closed without merging**
