### PR TITLE
Upgrade CNI to 0.6.0 in netplugin

### PR DESCRIPTION
**Pull request by vhosakot**
This PR upgrades CNI to `0.6.0` in netplugin. It has the following changes:

1. Update `ImportPath`, version and Rev (git commit SHA) in `Godeps.json` for CNI 0.6.0.
2. Update CNI version to `0.6.0` in the following k8s YAML files:
```
  install/k8s/contiv/contiv.yaml
  install/k8s/contiv/contiv_aci.yaml
  install/k8s/contiv/contiv_devtest.yaml
```
3. Replace legacy import path `appc/cni` with the correct import path `containernetworking/cni` in `k8s_cni.go ` and update required code to handle IPv4 and IPv6 addresses with CNI `0.6.0`.
4. Removed legacy vendor dir `netplugin/vendor/github.com/appc`.
5. Added new vendor dir `netplugin/vendor/github.com/containernetworking/cni` needed for CNI `0.6.0`.

Signed-off-by: Vikram Hosakote <vhosakot@cisco.com>

### CODE REVIEW

**Comment by vhosakot** [comment]
build PR

**Comment by vhosakot** [comment]
build PR

**Comment by vhosakot** [comment]
build PR

**Comment by vhosakot** [comment]
Green gate with CNI 0.6.0!

**Comment by vhosakot** [comment]
Since contiv 1.2 is released, this can be merged now.

**Comment by dojacobs** [comment]
build pr

**Comment by dojacobs** [comment]
build PR

**Comment by dojacobs** [comment]
build PR

**Comment by vhosakot** [comment]
build PR

**Comment by vhosakot** [comment]
build PR

**Comment by vhosakot** [comment]
build PR

**Comment by vhosakot** [comment]
Green gate ready for merge.

**Pull request merged**
