### PR TITLE
Makefile,drivers: Switch to using `gofmt -s` and correct areas where it does not pass

### PR DESCRIPTION
**Pull request by erikh**

### CODE REVIEW

**Comment by erikh** [comment]
same @abhinandanpb

**Comment by erikh** [comment]
nvm, more gofmt issues. I'll fix now.

**Comment by dseevr** [comment]
There's a few remaining in `utils/driverfactory.go`

**Comment by erikh** [comment]
this should probably be merged before anything else; reason being is that if someone merges in code this gofmt command will break on, it will break master.

(the rest of my patches are not critical)

**Comment by abhinandanpb** [comment]
LGTM.

**Pull request merged**
