### PR TITLE
objmodel changes

### PR DESCRIPTION
**Pull request by abhinandanpb**
Changes in netplugin to incorporate objmodel changes. Objmodel is split into 3 repos now contivmodel,objdb and modelgen.

Changes in makefile to generate contivmodel

### CODE REVIEW

**Comment by shaleman** [comment]
@abhinandanpb patch is too big to see on github. Can you create a gist with the diff and post a link here? 
Also sanity failed because of this error:
cd /opt/gopath/src/github.com/contiv/contivmodel/ && ./generate.sh && \
cp contivModel* ../netplugin/Godeps/_workspace/src/github.com/contiv/contivmodel/
/bin/sh: line 0: cd: /opt/gopath/src/github.com/contiv/contivmodel/: No such file or directory
make: *** [run-build] Error 1

you might want to run generate.sh in netplugin/Godeps/_workspace/src/github.com/contiv/contivmodel/ itself so that generated go files are in sync with imported json files.

**Comment by abhinandanpb** [comment]
https://gist.github.com/abhinandanpb/fd5417e93be02acd4d8e

**Comment by shaleman** [comment]
LGTM

**Comment by jainvipin** [comment]
@abhinandanpb, @shaleman 
Regarding the changes to generate the files in _workspace: is this a temporary workaround to allow coordination of rest of the objmodel repos?

**Comment by shaleman** [comment]
when objmodel repo was split, all generated code was removed from contivModel repo.
so, We have to regenerate the go code after godep importing it. Hence generating it inside Godeps workspace now. 

Removing generated code has two problems:
- After godep importing the contivModel, you still have to generate the go code
- People who want to use our go client can not just "go get contiv/contivmodel" and use it.

So, i'm submitting a pull request later today/tomorrow to keep the generated code in contiv/contivmodel.

**Comment by jainvipin** [comment]
> So, i'm submitting a pull request later today/tomorrow to keep the generated code in contiv/contivmodel.

+1 
Thanks for the explanation. I imagine this was done to keep things simpler and minimal however has some other side effects.

**Pull request merged**
