### PR TITLE
changing centos box version

### PR DESCRIPTION
**Pull request by abhinandanpb**
Updating to latest released version. Will need create a new box and bake in GuestAdditions and push it to atlas. Next PR.

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
@unclejack : I believe adding vboxguest additions was not recommended thing. I remember you have mentioned on some another PR description.

**Comment by abhinandanpb** [comment]
shared folders will not work without guest additions. Anyways this doesnt pertain to the current PR. Lets keep the discussion offline. All our images have guest additions.

**Comment by unclejack** [comment]
The CI run is irrelevant for this PR. Let's get it merged.

LGTM

**Comment by unclejack** [comment]
@jojimt Can you take a look at this and merge when you have the time, please?

**Comment by gaurav-dalvi** [comment]
@jojimt : Could you please merge this one ?

**Comment by jojimt** [comment]
I cannot merge because tests have failed.

**Comment by gaurav-dalvi** [comment]
@abhinandanpb : could you please re trigger ?

**Pull request merged**
