### PR TITLE
integrate client-go 5.0.0 in contiv

### PR DESCRIPTION
**Pull request by rchirakk**
vendor client-go 5.0.0 in contiv https://github.com/kubernetes/client-go

### CODE REVIEW

**Comment by rchirakk** [comment]
build PR

**Comment by rchirakk** [comment]
build PR

**Comment by unclejack** [comment]
build PR

**Comment by rchirakk** [comment]
build PR

**Comment by rchirakk** [comment]
first commit was with 4.0.0 & second commit was with 5.0.0
I will update the both msg to 5.0.0

**Comment by chrisplo** [comment]
i the first commit was actually 4.0.0 then the second upgraded, I guess that's fine, just I can't tell otherwise what happened, don't see versions in the first commit

**Comment by rchirakk** [comment]
build  PR

**Comment by rchirakk** [comment]
build PR

**Comment by rchirakk** [comment]
build PR

**Comment by rchirakk** [comment]
build PR

**Comment by dseevr** [comment]
Superseded by https://github.com/contiv/netplugin/pull/1063 since we want a different version and there are now merge conflicts here due to other PRs

**Comment by chrisplo** [comment]
did you mean #1087 @dseevr?

**Comment by dseevr** [comment]
Damnit.  Yes, edited.  (lol)

**Pull request closed without merging**
