### PR TITLE
Libnet service

### PR DESCRIPTION
**Pull request by DivyaVavili**
Adding service discovery to netplugin
- Service information is registered/deregistered when endpoints are created
- DNS support provided using SkyDNS/etcd and consul

### CODE REVIEW

**Comment by shaleman** [comment]
LGTM
merging this

**Comment by erikh** [comment]
tests aren't passing

**Comment by shaleman** [comment]
seems like a docker bug:
docker.go:75: Error 'Process exited with: 1. Reason was:  ()' launching container 'myContainer4', Output: 
		Error response from daemon: Cannot start container 708cd8ed6aeec20ec8ec1446af4b7834bcdac0641722f013872bb05eb1071a20: [8] System error: open /sys/fs/cgroup/devices/system.slice/docker-708cd8ed6aeec20ec8ec1446af4b7834bcdac0641722f013872bb05eb1071a20.scope/cgroup.procs: no such device

**Comment by erikh** [comment]
it is; an old one at that. we should re-run the tests any way I think?

**Comment by DivyaVavili** [comment]
All the test cases are passing on my local machine for both Ubuntu and Centos.

**Comment by DivyaVavili** [comment]
Looks like the diff is too huge. You can find the diff with only the relevant changes - godeps changes in this location: /ws/dvavili-sjc/svcplugin.diff

**Pull request merged**
