### PR TITLE
Godeps: update libopenflow to latest version

### PR DESCRIPTION
**Pull request by dseevr**
Signed-off-by: Bill Robinson <dseevr@users.noreply.github.com>

### CODE REVIEW

**Comment by dseevr** [comment]
build pr

**Comment by dseevr** [comment]
build pr

**Comment by unclejack** [comment]
@dseevr: Can you bump ofnet as well, please?

**Comment by dseevr** [comment]
@unclejack I did a `make godep-save` and, while it pulled in the latest HEAD on `ofnet` (after merging your PR), there were no file changes except the Jenkinsfile stuff that @nbartos added.  Nested vendor directories get flattened out I guess, so updating `libOpenflow` to the latest HEAD is sufficient.

**Pull request merged**
