### PR TITLE
Resolving issue #525

### PR DESCRIPTION
**Pull request by apoorva11029**
Added specific error statements for each function.

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
@apoorva11029 : Changes look good. Do we need argCheck function now ?
If not then please remove that.

**Comment by shaleman** [comment]
please remove argCheck() function if its not used anymore.
LGTM otherwise

**Comment by apoorva11029** [comment]
@gaurav-dalvi @shaleman removed argCheck.

**Comment by gaurav-dalvi** [comment]
LGTM !

**Pull request merged**
