### PR TITLE
use official docker client in mesos tests.

### PR DESCRIPTION
**Pull request by rchirakk**
fixes https://github.com/contiv/netplugin/issues/603
enable mesos integration tests

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
Do we need to use official docker client at other places in the code as well ?

**Comment by rchirakk** [comment]
only if it fails with the latest version of docker.

**Comment by gaurav-dalvi** [comment]
I think we should replace with official docker client everywhere in our code.

**Comment by rchirakk** [comment]
these tests require the latest client. it may not be necessary in other places.
yea, its good to move to the official client.

**Comment by gaurav-dalvi** [comment]
@rchirakk : Could you please take care of adding official docker client to all other places in the code ?

I am ok with other PR as well. for this PR : LGTM.

**Comment by jojimt** [comment]
LGTM

**Pull request merged**
