### PR TITLE
Remove references to deprecated code

### PR DESCRIPTION
**Pull request by shaleman**
- Remove references to old multi host demos which are deprecated now
- Remove references kubernetes integration

### CODE REVIEW

**Comment by erikh** [comment]
LGTM

**Comment by mapuri** [comment]
just wondering if should remove the corresponding files as well? otherwise LGTM

**Comment by shaleman** [comment]
@mapuri example directory is already removed. Are you referring to removing the .md files as well?

**Comment by mapuri** [comment]
ah, yes...I was referring to doc files.

**Comment by shaleman** [comment]
@mapuri i'll submit separate PR to remove unused .md files.

**Comment by jainvipin** [comment]
@shaleman - perhaps add new docs along with that too; that could be a docs pr

**Comment by jainvipin** [comment]
LGTM

**Pull request merged**
