### PR TITLE
Vagrantfile: bump Docker to 1.12.6

### PR DESCRIPTION
**Pull request by unclejack**
This bumps Docker to version 1.12.6. This is the latest version of Docker 1.12.

### CODE REVIEW

**Comment by gaurav-dalvi** [comment]
LGTM

**Comment by unclejack** [comment]
@jojimt: Can you take a look at this, please?

**Comment by gaurav-dalvi** [comment]
This has exposed this bug : https://github.com/contiv/netplugin/issues/691

**Comment by gaurav-dalvi** [comment]
But this PR is good to go.

**Comment by unclejack** [comment]
@jojimt Can you take a look at this when you have the time and merge it, please?

**Pull request merged**
