### PR TITLE
scripts/checks: adjust to ensure go 1.4.2 is in use

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

### CODE REVIEW

**Comment by mapuri** [comment]
@erikh 

Thinking more this change in itself might not actually work as the `checks` get triggered as part of build which happens inside the vm, so I think they will always succeed. May be we will need to add `checks` as part of `systemtest` target?
Other than that the change looks good.

++++++
And now some ranting ;)

I have a slight reservation with this stricter check that it might come as restricting for users running a slightly old or new version of go1.4 on host. We had similar check before and had to relax it as part of #30. Also I am not sure if current `systemtests` build fine for `mac` users, do you know? I remember @shaleman mentioned that systemtest still don't build on his mac but not sure if he is still hitting it.

Thinking about alternate approaches. I experimented with modifying the `system-test-singlehost` target as follows, which works on my server. But it will not work for `mac` users though. However, just wanted to share in case it seems better than a stricter version check and if we can't run `systemtests` mac for other reasons:

```
system-test-singlehost: clean run-build
     godep go test -v --timeout 30m -run "sanity" \
                      github.com/contiv/netplugin/systemtests/singlehost
```

**Comment by erikh** [comment]
It works for the host build, which IIRC was the problem. The restriction lives to keep people from building bad copies.

The systemtests do not work on mac -- they need the netlink library.

**Comment by mapuri** [comment]
> The restriction lives to keep people from building bad copies.

sgtm

we still need to add `checks` target as part of `systemtest`, right?

**Comment by erikh** [comment]
Yeah, probably a good idea. Let me amend this, one minute.

**Comment by erikh** [comment]
this should be ready after tests pass.

**Comment by erikh** [comment]
Anything left to do here?

**Comment by mapuri** [comment]
changes look good, it needs a rebase though.

**Comment by erikh** [comment]
once CI passes, let's merge this

**Comment by erikh** [comment]
@mapuri I merged this so we could move forward with @shaleman's changes. I'm going to do the same for the systemtests stuff today.

**Pull request merged**
