### PR TITLE
Integrate cntivModel and dockplugin with netplugin

### PR DESCRIPTION
**Pull request by shaleman**
This changes brings in contivModel and dockplugin into netplugin. 

With this change you can create network using contivModel and start doing "docker run --publish-service foo.network". Netmaster creates a default tenant and a "private" network at boot up. So, you can just start netmaster/netplugin and immediately start running containers with "docker run --publish-service foo.private" which starts containers in a private vxlan overlay without any additional config. 

Unfortunately, this works only on the host where net master is running since dockplugin still tries to use netdcli to talk to netmaster on localhost. Next phase of this change will remove this dependency and introduce an RPC between dockplugin and remote netmaster.

Summary of changes:
- Integrate contivModel
- merge dockplugin into netplugin. Change dockplugin to use .sock instead of .spec registration.
- Move to Veth pairs instead of OVS internal ports
- automatically create networks in docker daemon based on contivModel
- Query docker daemon using REST interface for network and endpoint parameters during endpoint creating
- Bring in libnetwork and associated libraries as godeps.
- temporarily Import libnetwork client library from coreOs guys till its merged into libnetwork.

### CODE REVIEW

**Comment by jainvipin** [comment]
@shaleman - a good leap, and some awesome sauce this change brings in; for some reason I can't see the diffs in github, because the changes are too big. I am eager to see the changes in the repo and check them out. Some comments based on your description here:

>    Integrate contivModel

With native/discrete management of various resources, comes the need to have backend code to handle various order of operations? We should add tests to ensure the order of operations are covered in all situations.

>    merge dockplugin into netplugin. Change dockplugin to use .sock instead of .spec registration.

I assume there is one binary on the host now, And a go-routine perhaps listening to the dockplugin(dockcontivnet) tasks.

>   Move to Veth pairs instead of OVS internal ports

Let's track this issue of using the internal ports separately. One of us can file the issue.

>   automatically create networks in docker daemon based on contivModel

cool.

>    Query docker daemon using REST interface for network and endpoint parameters during endpoint creating

Were you able to query docker daemon about the container during endpoint creation?

>    Bring in libnetwork and associated libraries as godeps.
>    temporarily Import libnetwork client library from coreOs guys till its merged into libnetwork.

much needed to get going...

**Comment by shaleman** [comment]
Github is not showing all the diffs since lib network godep dependencies are too large.
Here is just the relevant part of the diff.

https://gist.github.com/shaleman/e133144053fd4886dd6f



Were you able to query docker daemon about the container during endpoint creation?

Yes, I can access lib network REST endpoints during remote plugin callback. This includes things like network name, service name etc. But, I can’t get any info about the container itself(docker daemon runs into a deadlock if I try to do ‘docker inspect’ during callbacks). Network name and service names are good enough for now.


Overall libnetwork is still not quite mature. For example:

  1.  You can’t delete an endpoint
  2.  You can’t delete a network once you create an endpoint on it.
  3.  Even though remote drivers are global scope, networks are not synced across the cluster(Mainly missing documentation on how to link libnetwork to consul)

-sukhesh

**Comment by shaleman** [comment]
Can one of you take a look at this change?
Diffs excluding the Godeps stuff is at:
https://gist.github.com/shaleman/e133144053fd4886dd6f

**Comment by mapuri** [comment]
@shaleman Itlooks like I can't post comments on the gist.

Any chance you can squash your commits? That way I think I can just look at the diffs in your private branch and comment there.

**Comment by erikh** [comment]
When you squash this, please squash the godeps changes (or rewrite your branch) into a single commit, so we can view the rest here.

**Comment by shaleman** [comment]
With the help of google, I figured out how to squash multiple commits into one. It doesn’t really help because libnetwork  is too large for github to show. You still can’t see or comment on the relevant diffs.

So, how do I "squash the godeps changes (or rewrite your branch) into a single commit”?

-sukhesh

**Comment by shaleman** [comment]
Closing this one in favor of #145

**Pull request closed without merging**
