### PR TITLE
[WIP] Support secure etcd connection with tls cert

### LINKED ISSUE #777: Proposal: support to run against secured etcd
In production, ETCD should be secured with TLS to ensure the security and stability, but Contiv currently does not support secured etcd. This is an essential feature when use Contiv in produtin, any plan to support this?

### PR DESCRIPTION
**Pull request by BSWANG**
#### Fixes #777 
Please describe:
- support secure etcd connection with tls cert
- manual tested on secure etcd server

## TODO
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by dseevr** [comment]
build pr

**Comment by kahou82** [comment]
build PR

**Comment by kahou82** [comment]
@BSWANG I would like to understand more how you want to use Contiv netplugin. Do you mind to discuss more via email?

**Comment by dseevr** [comment]
@BSWANG This PR is hitting a compile error here:

```
# github.com/contiv/netplugin/netmaster/objApi
netmaster/objApi/objapi_test.go:137: not enough arguments in call to NewAPIController
```

You can leave this PR open and just force push your branch when you make changes.  There's no problem with that.

If you want to run the tests locally, you can run `make system-test`.  It will spin up 3 VMs using VirtualBox and run all the tests.  You will need 16gb ram, though.  It will be faster than waiting for us to check our CI and post the errors here.  😃

**Pull request closed without merging**
