### PR TITLE
Update Godeps (objdb, etcd, logrus, etc.)

### PR DESCRIPTION
**Pull request by dseevr**
Includes logrus and etcd (2.3.8) updates.  I tested this locally and it all passes, but we'll let CI be the final determiner of that.

Related: https://github.com/contiv/objdb/pull/20, https://github.com/contiv/modelgen/pull/15

### CODE REVIEW

**Comment by dseevr** [comment]
Whoops, you're right.  I'll update the title and the commit message

**Comment by dseevr** [comment]
@jojimt Ahh, I meant `contivmodel`, not `modelgen`.   This is passing now

**Comment by dseevr** [comment]
@jojimt this is ready to go

**Comment by jojimt** [comment]
Yes, I want to wait for a day before merging it

**Comment by dseevr** [comment]
Fine with me 👍

**Pull request merged**
