### PR TITLE
use netplugin-build for compile container name

### PR DESCRIPTION
**Pull request by chrisplo**
Signed-off-by: Chris Plock <chrisplo@cisco.com>

### CODE REVIEW

**Comment by unclejack** [comment]
@chrisplo: Isn't this made redundant by #1012? It makes the same changes.

**Comment by chrisplo** [comment]
the intent is this goes before #1008, #1012, I'll merge or rebase the other PRs after this lands

**Comment by dseevr** [comment]
build pr

**Comment by chrisplo** [comment]
build PR

**Pull request merged**
