### PR TITLE
Aci integ

### PR DESCRIPTION
**Pull request by jojimt**
This PR brings in the changes for ACI integration.

Summary of changes:

1) Added a hook into AppCreate for posting app-profiles based on composition
2) Added support for per-EPG vlan allocation
3) Added contivctl support for enabling/disabling the above
4) godep update to bring in changes to objmodel (note this resulted in a bunch of unused components being deleted from Godep/_workspace, and those show up in the diff)

Testing:
1) Verified sanity after rebase
2) Verified aci and non-aci functionality using the contivctl to configure.

### CODE REVIEW

**Comment by jainvipin** [comment]
@jojimt: will the removal of various javascript files make the front page rendering that is otherwise available?

**Comment by jojimt** [comment]
I ran it by Sukhesh yesterday and he gave the go ahead. @shaleman can you please comment?

**Comment by jainvipin** [comment]
perhaps he is working on regenerating them in objmodel... will let him comment

**Comment by shaleman** [comment]
These particular files are not needed for Web UI rendering(They are only required for building web UI javascript bundle).
They were accidentally checked in because i had manually copied objmodel into godep directory at some point. Its good they are getting cleaned up now.

**Comment by jojimt** [comment]
Are you able to see the diffs? Looks like my real diffs are drowned out by the Godeps.

**Comment by jojimt** [comment]
I have created a diff file without the extraneous stuff. It's available at contiv141:/home/ladmin/pull_173.diff

**Comment by jojimt** [comment]
Can someone help merge this?

**Pull request merged**
